profile:
  active: convergent-dev:convergent-dev
config:
  providers:
  - module: provider-anthropic
    config:
      default_model: claude-sonnet-4-5
      beta_headers: context-1m-2025-08-07
      api_key: ${ANTHROPIC_API_KEY}
      priority: 1
    source: git+https://github.com/microsoft/amplifier-module-provider-anthropic@main
